### ISSUE TITLE
arm64 version

### ISSUE THREAD

**Issue by alain-lnpcrd** [iRobotEducation/create3-docker#4]
Hi,
Owner of a raspberry-pi, what should be done to obtain an arm64 version?

**Comment by alsora** [comment]
The images currently provided by this repository are meant for desktop machines.
Indeed they include visualization tools and simulators.

At the moment, i don't see any need for an arm64 image to be used on embedded devices.

You should just use a standard ros2 core docker image, such as `osrf/ros:galactic-core`.
Note that you will need to add the `irobot_create_msgs` package to be able to interact with the robot.

**Comment by brianlmerritt** [comment]
If you are trying to run ROS2 on the create3, then this docker repository is not what you want.  Clone https://github.com/iRobotEducation/irobot_create_msgs after installing ROS2 galaxy or humble (Ubuntu version dependent) and launch that.

**Comment by alsora** [comment]
@alain-lnpcrd FYI: we just pushed an arm64 docker image for ROS 2 Humble.
```
docker pull irobotedu/create3-humble:latest
```

However, the main purpose for this image is to be used on arm64 Mac OS machines.
You shouldn't use this docker image on a Raspberry-Pi and, my personal opinion, you shouldn't use docker at all for your use case.
I'm closing this ticket.
