### ISSUE TITLE
Failed clone repo

### ISSUE THREAD

**Issue by dbortoluzzi** [iRobotEducation/create3-docker#5]
https://github.com/iRobotEducation/create3-docker/blob/49f87df3b487e8dec3c67671c1342a0178b59ed1/create3-humble/Dockerfile#L64

I think you to change the line, as:

```shell
RUN git clone -b humble https://github.com/iRobotEducation/create3_sim.git
```

**Comment by alsora** [comment]
Yes, thanks.
Now humble is officially supported but I haven't updated this yet.

Note that you don't need to build these dockerfiles locally, as they are uploaded to Docker hub

**Comment by alsora** [comment]
@dbortoluzzi I updated the dockerfile with the correct packages.
I will upload docker images to the hub in the next days.

**Comment by alsora** [comment]
The updated ROS 2 Humble Docker image has been pushed to the Docker hub.
To use it:
```
docker run -it --rm --network=host --privileged -e DISPLAY=$DISPLAY irobotedu/create3-humble
```
