### ISSUE TITLE
Broken link in create3-humble/Dockerfile for demo.repos

### ISSUE THREAD

**Issue by lilblueyes** [iRobotEducation/create3-docker#7]
Hello,

I noticed that the following link in the `create3-humble/Dockerfile` is no longer functional:

```dockerfile
RUN wget https://raw.githubusercontent.com/iRobotEducation/create3_sim/main/irobot_create_gazebo/demo.repos \
```

This link should be replaced with:

```dockerfile
RUN wget https://raw.githubusercontent.com/iRobotEducation/create3_sim/humble/irobot_create_gazebo/demo.repos \
```

The updated link will correctly download the `demo.repos` file required for the Create 3 simulation.

**Comment by alsora** [comment]
Thank you @lilblueyes for the ticket.
I fixed the link in https://github.com/iRobotEducation/create3-docker/commit/40424c5ef4bf904a17206d2db9117b638bab8769
